"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# (optional but typical)
STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']  # if you have a project-level /static

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o^2qco(snue16g)cyl$iaz^lxaxsozb+@&pl0ii&#bxww_18au'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts and CSRF trusted origins are configurable via env for easy sharing
# Example (PowerShell):
#   $env:ALLOWED_HOSTS = "127.0.0.1,localhost,192.168.1.23,example.ngrok-free.app"
#   $env:CSRF_TRUSTED_ORIGINS = "https://example.ngrok-free.app"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# In DEBUG, allow ngrok by default to simplify sharing
if DEBUG:
    if '.ngrok-free.app' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS += ['.ngrok-free.app']  # matches any subdomain
    if 'CSRF_TRUSTED_ORIGINS' in globals():
        if 'https://*.ngrok-free.app' not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS += ['https://*.ngrok-free.app']
    else:
        CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',  # Replace 'myapp' with your actual app name
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mywebsite.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR/'myapp/template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR/'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home-page"   # change "home" to your homepage route
LOGOUT_REDIRECT_URL = "login"

# DEBUG = True         # only to test custom error pages locally if you want
# ALLOWED_HOSTS = ['*']   # or your domain/IP in production
# # at bottom of the file (global scope)
handler404 = 'myapp.views.handler404'

# Require login for the whole site except the following paths
LOGIN_EXEMPT_URLS = (
    r'^/login/$',
    r'^/register/$',
    r'^/static/.*',
    r'^/media/.*',
    r'^/admin/login/.*',
    r'^/admin/.*',
)
