# Generated by Django 5.2.5 on 2025-10-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_picture_product_specfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDetail', models.TextField()),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact')),
            ],
        ),
    ]
