# Generated by Django 5.2.5 on 2025-10-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='Contact',
            new_name='contact',
        ),
    ]
