# Generated by Django 5.2.5 on 2025-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_contact_action_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
